### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EfetureLuckyEsiri** [sodsegxy/september2019#1]
Hi Segun
I have sent several messages to your yahoomail with no answer .Please I need your help with regard to my WebDriver not been able to import since last class I have not been able to do anything and even Steve is not replying my message too .Please get back
Thanks
Efe

**Comment by sodsegxy** [comment]
Hi,
I'm sorry for your trouble, I have been busy. My direct email is sodiqolusegun@yahoo.co.uk. We will solve the problem this week. I am engaged Monday and Tuesday, let's hook Wednesday after pm. Thank you

**Comment by EfetureLuckyEsiri** [comment]
Dear Segun
Am still waiting to hear from you please get back with a time to
help fix that web driver problem ,since then I have not practice
and I think am losing everything you taught me.
Thanks
Lucky
